name: cotiz
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sizer: ^3.0.5
  google_fonts: ^6.2.1
  intl_phone_number_input:
    git:
      url: https://github.com/Shahidbangash/intl_phone_number_input.git
      ref: develop
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  gap: ^3.0.1
  http: ^1.2.2
  pinput: ^5.0.0
  syncfusion_flutter_gauges: ^27.2.4
  qr_flutter: ^4.1.0
  qr_code_scanner_plus: ^2.0.6
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
